### ISSUE TITLE
Crear algunas clases "modelos"

### ISSUE THREAD

**Issue by brundows** [sebastianjorc/TiendaVirtualMusical#1]
La idea de esto, es utilizar una forma similar de desarrollo a la de DAA, pero esta vez, basándonos en ideas que hemos tenido desde la creación del Diagrama ER o algo por el estilo, algo como:
* Cancion
* Album
* Artista
(Y más...)

Para utilizarlos como clases modelos o clases que serán utilizadas para rellenar los datos que se obtengan en consultas.

**Comment by sebastianjorc** [comment]
Es realmente necesario crear estas clases?
Digo, debería ser posible editar y mostrar los datos solamente mediante consultas. El almacenarlos en el programa puede hacer más lento el proceso.

**Comment by brundows** [comment]
Pienso que es necesario en el sentido de que necesitamos retener datos de alguna forma; ya que puede que nos encontremos con situaciones de representar los datos en algún componente de Swing (ej: JTable y un TableModel personalizado). 
Además, creo que puede ser un plus para el trabajo en grupo, permitirá una mayor comprensión de lo que se hace. 
Ojo, no necesariamente se tendría que hacer todas las entidades del diagrama, ni tampoco necesario que se rellenen todas las clases bases y variables altiro en una consulta.

**Comment by brundows** [comment]
Gran porcentaje se realizó en el commit 2420280c8e900264d1f7305864ef753a6ad9987e; actualmente están desarrolladas de forma básica (mayormente getters & setters) las clases Álbum, Artista, Cancion, Usuario, Producto. Se planea hacer más acorde a lo que se esté desarrollando en el camino.

**Comment by brundows** [comment]
Las principales clases modelos que se relacionan con (prácticamente) todas las funcionalidades de la tienda, están creadas, junto a su exitosa implementación de funciones consultoras, dentro de ellas. Esta issue puede cerrarse.
